config/routes.rb
Rails.application.routes.draw do

  root 'graphs#index'

  resources :graphs, only: [:index]
  get 'graphs/:gene/:graph' => 'graphs#show', as: :graph

  resources :feedback, only: [:create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def create
    FeedbackMailer.send_feedback(params[:feedback]).deliver_now
  end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  # show graphs for a gene
  def index
    @graphs = Graph.all_in_gene(params[:gene] || 'global')

    # share tsv paths needed for each graph with javascript
    tsv_paths = {}
    @graphs.each do |graph|
      tsv_paths[graph.graph] = graph.tsv_path
    end
    gon.tsv_paths = tsv_paths
  end

  # show interactive graph
  def show
    @graph = Graph.new(params[:gene], params[:graph])
    gon.tsv_paths = { @graph.graph => @graph.tsv_path }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_static_graph.html.haml
- content_for :graph_js do
  = javascript_include_tag graph.js_path, 'data-turbolinks-track' => true

.graph{ class: "#{graph.graph}" }
= link_to graph_url(gene: graph.gene, graph: graph.graph), class: 'text' do
  %h2.squaretxt= graph.title
  %p= graph.short_description

app/views/graphs/index.html.haml
%tag.class#id{name: 'this', value: 'that'}
.container-fluid#page_content
  .row
    .col-lg-12
      %h1.land.welcome
        Welcome to
        %b VisualizeClinvar!
      %p.land We help you make sense of the data in ClinVar <br/> so you can make sense of discoveries
  .row
    .col-lg-12
      %form.col-lg-10
      .form-group
        %input#exampleSearchBar.hidden.cvform-control{:placeholder => "Enter a gene", :type => "text"}
        %button.hidden.cvbtn Search
  .container
    - @graphs.insert(0, @graphs.delete_at(@graphs.find_index { |g| g.graph == 'phenoJungle' }))
    / Apologies for the hack to get phenoJungle to use two columns.
    - (@graphs.size/3.0).ceil.times do
      .row.row-eq-height.graph-row
        - 3.times do
          - if @graphs.empty?
            .col-md-4.col-xs-4
              .white-mother
          - else
            - graph = @graphs.pop
            - if graph.graph == 'phenoJungle'
              .col-md-8.col-xs-8
                .blue-mother
                  = render 'static_graph', graph: graph
            - else
              .col-md-4.col-xs-4
                .blue-mother
                  = render 'static_graph', graph: graph

app/views/graphs/show.html.haml
/- provide(:graph_js, @graph.js_path)
- content_for :graph_js do
  = javascript_include_tag @graph.js_path, 'data-turbolinks-track' => true

.container-fluid
  .row
    .col-md-12
      .page-header.text-center
        %h1
          = @graph.title
          %br
          %small= @graph.short_description
  .row.graph-container
    .col-md-6.col-md-offset-3
      .graph{ class: "#{@graph.graph}" }

  .row.description-container
    .col-md-6.col-md-offset-3
      %p= @graph.long_description

  .row.text-center.graph-info-container
    .col-md-2.col-md-offset-3.graph-info
      Last updated:
      %br
      %strong= @graph.updated
    .col-md-2.graph-info
      Primary author:
      %br
      %strong= @graph.author
    .col-md-2.graph-info
      Graph type:
      %br
      %strong= @graph.type

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title VisualizeClinvar
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = content_for :graph_js
    = csrf_meta_tags
  %body{ class: "#{controller.controller_name} #{action_name}" }
    .container-fluid
      .row
        .col-lg-12
          .logo
            = link_to image_tag( 'visualizeClinvarLogo.png'), root_url, class: 'pull-left'
          .head_links
            %a.head.feedback{href: "#", data: { toggle: "modal", target: "#feedback-modal" }} Feedback
            = link_to 'About', page_path('about')

    = yield

    .row
      =image_tag "footer_design.png", :class => "footer_design"

    %nav.footer.navbar.navbar-default.text-center
      .container-fluid
        .row
          = link_to 'About', page_path('about'), class: 'foot'
          %a.foot{href: "#", data: { toggle: "modal", target: "#feedback-modal" }} Feedback
          %a.foot.hidden{ href: "#donate" } Donate
        .row
          %p.copyright © Visualize ClinVar 2015
    = render 'shared/feedback_modal'

app/views/pages/about.html.haml
<!DOCTYPE html>
%html
	.top.text-center
		%h1.teamname
			%strong The Team
		%p.blurb
			%i ClinVar is a free variant knowledge-base service provided by the NCBI.
			%br
			%i We provide visualizations of the data to support discovery.
	.container
		.row.team-row
			.col-md-1.col-xs-1
			.col-md-2.text-right.col-xs-2
				= image_tag "welch.png", :class => "img-responsive"
			.col-md-3.col-xs-3
				%h4
					%strong Brandon Welch
					%p
						%br
						Project Lead, Genetics 
						%br
						Domain Expert, Database Design
					%a
						= link_to image_tag("https://static.licdn.com/scds/common/u/img/webpromo/btn_profile_bluetxt_80x15.png"), 'https://www.linkedin.com/in/welchbm', :target => "_blank", :alt => "View Brandon Welch's profile on LinkedIn", :class => "linkedin" 
			.col-md-2.text-right.col-xs-2
				= image_tag "heale.png", :class => "img-responsive"
			.col-md-3.col-xs-3
				%h4
					%strong Bret Heale
					%p
						%br
						Data-modeling, Genetics
						%br
						Domain Expert, D3-developer
					%a
						= link_to image_tag("https://static.licdn.com/scds/common/u/img/webpromo/btn_profile_bluetxt_80x15.png"), 'https://www.linkedin.com/pub/bret-heale-phd/26/53b/7ab', :target => "_blank", :alt => "View Bret Heale's profile on LinkedIn", :class => "linkedin" 
			.col-md-1.col-xs-1
	.box
		

app/views/shared/_feedback_modal.html.haml
.modal.fade#feedback-modal{ tabindex: "-1", role: "dialog", "aria-labelledby" => "Feedback" }
  .modal-dialog{ role: "document" }
    .modal-content
      = form_tag("/feedback", method: "post", remote: "true") do
        .modal-header
          %button.close{ type: "button", data: { dismiss: "modal" }, "aria-label" => "Close" }
            %span{ aria: { hidden: 'true' }} &times
          %h4.modal-title
            Tell us what you think!
        .modal-body
          .row.form-group
            .col-sm-6
              = text_field_tag "feedback[name]", "", placeholder: "Name", class: "form-control"
            .col-sm-6
              = email_field_tag "feedback[email]", "", placeholder: "example@email.com", class: "form-control"
          .row.form-group
            .col-sm-6
              = text_field_tag "feedback[institution]", "", placeholder: "Institution (optional)", class: "form-control"
            .col-sm-6
              = telephone_field_tag "feedback[phone]", "", placeholder: "Phone (optional)", class: "form-control"
          .row.form-group
            .col-sm-12
              = text_area_tag "feedback[comment]", "", placeholder: "Your feedback", rows: 5, class: "form-control"
        .modal-footer
          %input.btn.btn-success{ type: "submit", value: "Submit" }